name: loan_calc
description: LoanCalc é uma biblioteca em Dart para cálculo de empréstimos, incluindo o cálculo de parcelas, IOF, TAC e XIRR (Taxa Interna de Retorno Anualizada).
version: 1.0.0+1
license: MIT
homepage: https://github.com/Philippenau-Dev/loan_calc

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  xirr_flutter: ^1.0.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0


flutter:

